In [ ]:
import os

In [ ]:
os.listdir()

['.config', '.ipynb_checkpoints', 'AL_C-small - Copy.csv', 'sample_data']

In [ ]:
import pandas as pd
import csv

In [ ]:
df = pd.read_csv("/content/AL_C-small.csv", sep=';', engine='python',encoding="utf-8")

In [ ]:
df.head()

,rowid,message_date,username,about,message_detail,tweet_id,account_creation_date,followers,token,gender,...,internal_id,language,location,message_url,platform_type,received_timestamp,retweet_count,retweet_id,tweets,date
0,24383,01.10.2023 00:06,CgadaHi,Halil İbrahim ceyhan ♥️,HALİL İBRAHİM CEYHAN MENTİON ETKİNLİĞİ 📌HEDEF📌...,"1,70823E+18",14.07.2022 16:37,259,333,F,...,TWT202310011708226783424774544,tr,Türkiye,https://twitter.com/CgadaHi/statuses/170822678...,Twitter,02.10.2023 05:38,42,0,92861,01.10.2023
1,26605,01.10.2023 00:18,LeonorO43665348,NaN,RT @GunesiTurk: ⛔️ DISPONIBLE ⛔️ PELICULA #Dar...,"1,70823E+18",17.04.2021 19:33,318,352,F,...,TWT202310011708229877822878132,es,NaN,https://twitter.com/LeonorO43665348/statuses/1...,Twitter,04.10.2023 05:37,0,"1,70823E+18",182894,01.10.2023
2,24382,01.10.2023 00:24,Akbuluttsonerr,🅶🅰🅻🅰🆃🅰🆂🅰🆁🅰🆈 💛🦁♥️✍️📖🄰🄷🄼🄴🅃 🄺🄰🅈🄰 🎶📚 🎶🎶🎶🎶🎶🎤🅂🄴🄻🄳🄰 🄱...,Geldim fener trolleri anlat https://t.co/gHyE...,"1,70823E+18",14.03.2023 10:05,2859,2743,U,...,TWT202310011708231349859938629,tr,Canada,https://twitter.com/Akbuluttsonerr/statuses/17...,Twitter,02.10.2023 05:38,2,0,3727,01.10.2023
3,24381,01.10.2023 00:49,yunusmiroglu34_,NaN,benim motivasyonum eleştiri mesleğe böyle başl...,"1,70824E+18",31.08.2018 00:55,562,423,M,...,TWT202310011708237768231436631,tr,NaN,https://twitter.com/yunusmiroglu34_/statuses/1...,Twitter,02.10.2023 05:38,20,0,9537,01.10.2023
4,26573,01.10.2023 04:48,bomberosCBQ,Cuerpo Bomberos Quilpué Abnegación y Discipl...,"EMERGENCIA: 22:48 CLAVE 6-5 (RESCATE), AVENIDA...","1,7083E+18",11.03.2011 16:17,20179,149,U,...,TWT202310011708297738834542991,es,Chile,https://twitter.com/bomberosCBQ/statuses/17082...,Twitter,02.10.2023 05:38,3,0,11996,01.10.2023

In [ ]:
df.count()

rowid                    29
message_date             29
username                 29
about                    19
message_detail           29
tweet_id                 29
account_creation_date    29
followers                29
token                    29
gender                   29
hashtag                   5
image_url                 8
internal_id              29
language                 29
location                 15
message_url              29
platform_type            29
received_timestamp       29
retweet_count            29
retweet_id               29
tweets                   29
date                     29
dtype: int64

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.44.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.24.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.8.30)

In [ ]:
from transformers import pipeline, AutoModelForTokenClassification, AutoTokenizer, AutoModelForSequenceClassification

In [ ]:
tokenizer= AutoTokenizer.from_pretrained("savasy/bert-turkish-text-classification")
model= AutoModelForSequenceClassification.from_pretrained("savasy/bert-turkish-text-classification")

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [ ]:
nlp=pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [ ]:
nlp("bla bla")

[{'label': 'culture', 'score': 0.4753016233444214}]

In [ ]:
nlp("bla bla")[0]['label']

'culture'

In [ ]:
import datetime
date1= datetime.datetime.now()
print("Start:" + str(date1))

for ind in df.index:
  #df.loc[index, 'sentiment']=nlp(df.loc[index, 'text'])[0]['label']
  category=nlp(df.loc[ind, 'message_detail'])[0]['label']
  df.loc[ind,'category']=category

date2= datetime.datetime.now()
print("End:"+ str(date2))
dateSon=date2-date1
print("Diff"+ str(dateSon))

Start:2024-10-20 21:01:23.798176
End:2024-10-20 21:01:33.233448
Diff0:00:09.435272

In [ ]:
df.head()

,rowid,message_date,username,about,message_detail,tweet_id,account_creation_date,followers,token,gender,...,language,location,message_url,platform_type,received_timestamp,retweet_count,retweet_id,tweets,date,category
0,24383,01.10.2023 00:06,CgadaHi,Halil İbrahim ceyhan ♥️,HALİL İBRAHİM CEYHAN MENTİON ETKİNLİĞİ 📌HEDEF📌...,"1,70823E+18",14.07.2022 16:37,259,333,F,...,tr,Türkiye,https://twitter.com/CgadaHi/statuses/170822678...,Twitter,02.10.2023 05:38,42,0,92861,01.10.2023,culture
1,26605,01.10.2023 00:18,LeonorO43665348,NaN,RT @GunesiTurk: ⛔️ DISPONIBLE ⛔️ PELICULA #Dar...,"1,70823E+18",17.04.2021 19:33,318,352,F,...,es,NaN,https://twitter.com/LeonorO43665348/statuses/1...,Twitter,04.10.2023 05:37,0,"1,70823E+18",182894,01.10.2023,culture
2,24382,01.10.2023 00:24,Akbuluttsonerr,🅶🅰🅻🅰🆃🅰🆂🅰🆁🅰🆈 💛🦁♥️✍️📖🄰🄷🄼🄴🅃 🄺🄰🅈🄰 🎶📚 🎶🎶🎶🎶🎶🎤🅂🄴🄻🄳🄰 🄱...,Geldim fener trolleri anlat https://t.co/gHyE...,"1,70823E+18",14.03.2023 10:05,2859,2743,U,...,tr,Canada,https://twitter.com/Akbuluttsonerr/statuses/17...,Twitter,02.10.2023 05:38,2,0,3727,01.10.2023,technology
3,24381,01.10.2023 00:49,yunusmiroglu34_,NaN,benim motivasyonum eleştiri mesleğe böyle başl...,"1,70824E+18",31.08.2018 00:55,562,423,M,...,tr,NaN,https://twitter.com/yunusmiroglu34_/statuses/1...,Twitter,02.10.2023 05:38,20,0,9537,01.10.2023,sport
4,26573,01.10.2023 04:48,bomberosCBQ,Cuerpo Bomberos Quilpué Abnegación y Discipl...,"EMERGENCIA: 22:48 CLAVE 6-5 (RESCATE), AVENIDA...","1,7083E+18",11.03.2011 16:17,20179,149,U,...,es,Chile,https://twitter.com/bomberosCBQ/statuses/17082...,Twitter,02.10.2023 05:38,3,0,11996,01.10.2023,technology

In [ ]:
file_name= "/content/son.csv"
df.to_csv(file_name, encoding='utf-8', index=False)